language: python

python:
  - "3.5.4"

install:
  - pip install -r requirements.txt
  - pip install -e .

script:
  - pytest -vs tests/

env:
  - TRAVIS_BUILD_DIR=$TRAVIS_BUILD_DIR

before_install:
  - echo "$PATH"
  - echo "$TRAVIS_BUILD_DIR"

notifications:
  - email: false
